import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import { firestore } from '@/utils/firebase';
const inter = Inter({ subsets: ['latin'] });

//firebase
import { doc, setDoc } from 'firebase/firestore';
import Layout from '@/components/Layout';

const documentReference = doc(firestore, 'users/patient');
function writeUser() {
  const userData = {
    name: 'john',
    lastName: 'pigeon',
  };
  setDoc(documentReference, userData);
}
writeUser();
console.log('loaded');
//firebase
export default function Home() {
  return (
    <Layout home>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-app.js"></script>
        <script src="https://www.gstatic.com/firebasejs/8.10.1/firebase-firestore.js"></script>
      </Head>
      <main>
        <h2>Todos</h2>
      </main>
    </Layout>
  );
}
